# Generated by Django 3.1.7 on 2021-03-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20210320_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_saved',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sub_saved',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sub_saved',
        ),
    ]
