# Generated by Django 3.1.7 on 2021-03-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_product_sub_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutriscore_grade',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
