# Generated by Django 3.1.7 on 2021-03-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20210326_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_saved',
            old_name='product',
            new_name='sub',
        ),
    ]
