# Generated by Django 3.1.7 on 2021-03-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20210330_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='sub_saved',
            options={'verbose_name': 'Sub_saved'},
        ),
    ]
