# Generated by Django 3.1.7 on 2021-03-31 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20210331_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['nutriscore_grade'], 'verbose_name': 'Product'},
        ),
    ]
