# Generated by Django 3.1.7 on 2021-04-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20210331_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_saved',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='sub_saved',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sub_saved',
        ),
    ]
