# Generated by Django 3.1.7 on 2021-04-01 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0010_auto_20210401_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField(null=True)),
                ('categories', models.CharField(max_length=500)),
                ('nutriscore_grade', models.CharField(max_length=5, null=True)),
                ('image_nutriments', models.URLField(max_length=1500)),
                ('barcode', models.CharField(max_length=30)),
                ('url', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['nutriscore_grade'],
            },
        ),
        migrations.CreateModel(
            name='Sub_saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub_saved',
            },
        ),
    ]
